.\" Process this file with
.\" groff -man -Tascii <filename>
.\" or
.\" man ./<filename>
.\"
.\" For info on groff, type 'man groff', 'info groff', or go to
.\" https://www.gnu.org/software/groff/
.\"
.TH resume 7 "9 June 2025" "1.0" "Carmelo Califano's Resume"
.SH NAME
Carmelo Califano's ResuMan (Resume as Man page)
.SH SYNOPSIS
SaaS = Security as-a-Service! Let's start with RFC5321.
.SH DESCRIPTION
.IP "Cisco"
.IP "2022-now: Customer Success Specialist (Designated Service Manager)" 0.4i
Fostering innovation and customer success across Cisco's global Software Support Services Collaboration and Security customers. 

Helping customers accelerate security adoption and utilization. 

Delivering technical onboarding and adoption support through product and service life-cycle.
.IP "2001-2022: Consulting Engineer" 0.4i
Consultancy, design, and deployment focusing on OSS/BSS/NMS targeting Service Providers worldwide, IAM and AAA (RADIUS, Diameter), DDI (focusing on DNS and DHCP), virtualization of existing infrastructure, process automation.
.IP "Self employed 2010-2011" 0.4i
Network security recurring audits.
.PP
.SH OPTIONS
.IP "CISSP" 0.4i
ISC2, 04/2025
.IP "AWS Certified Cloud Practitioner (since 2021)" 0.4i
Valid until: 09/2027
.IP "Certified in Cybersecurity" 0.4i
ISC2, 07/2024
.IP "Generative AI Blue Belt" 0.4i
Cisco, 03/2024
.IP "OCP for Cybersecurity professionals" 0.4i
Graduate School of Management (GSoM), Politecnico di Milano, Milan, Italy, 2022-23
.IP "Cybersecurity Essentials" 0.4i
Cisco, 07/2022
.IP "Tech lead and mentor" 0.4i
AAA/IAM, RADIUS, Diameter (3G/4G), DNS, DHCP
.IP "Cisco Certified DevNet Associate"
Class of 2020
.IP "Full stack (hardware, hypervisor, OS, application) design and delivery of low-latency (e.g. BGP Anycast), highly-available and distributed DNS networks, characterized by robustness and resiliency. Somewhere in the world about 30,000,000 end users rely on a service I built for them many (many!) times per day."
.IP "Full stack design and delivery of secure AAA solutions (RADIUS/Diameter) handling thousands to millions of end users."
.IP "MS in Electronic Engineering" 0.4i
Universita' di Napoli Federico II, Naples, Italy
.SH EXAMPLES
.IP "Discover Cyber" 0.4i
.RS
seminar + CTF at Politecnico di Milano, 04/2025
.RE
.IP "Dissecting Artificial Intelligence" 0.4i
.RS
public speech at University of Verona, 05/2024
.RE
.RS
public speech at University of Trento, 05/2024
.RE
.SH BUGS
I'm very much interested in Open Source and related technologies: coding, (white-hat) hacking, OSs (Linux, *BSD, Amiga, Haiku...). SBCs (Arduino, Raspberry Pi...) are my favourite tools when wearing my "maker" hat.
.PP
I love reading, fiction, essays, going to movies, theatre and museums but, above all, travelling and visiting interesting places.
.SH AUTHOR
.IP LinkedIn 0.4i
https://www.linkedin.com/in/carmelo/
.IP Keybase 0.4i
https://keybase.io/carmelo
.IP Bluesky 0.4i
https://bsky.app/profile/carmelo0x63.bsky.social
.IP Mastodon 0.4i
https://mastodon.sdf.org/@carmelo
.SH SEE ALSO
25 years supporting Service Provide and Enterprise clients worldwide. No routing, switching, BGP, OSPF, pretty please... my domains are infrastructure, servers, virtualization, operating systems, identity and access management (IAM), authentication, authorization and accounting (AAA), complex software applications and the data flows that feed them.
Above all, SECURITY, in the wider sense. Systemic security goes beyond protecting the perimeter with firewalls and IPSs. Application/cloud security comes from automation, IaC, supply chain analysis, redundancy, compliance, treating your apps/servers as disposable entities (the "pet vs. cattle" metaphor), active monitoring, remediation, and more.
.PP
.I Yearly figures as an individual contributor:
.RS
- value of managed services: 500k-1M USD yearly range
.RE
.RS
- end-users relying on my services: several millions
.RE
